# Data Manipulation using Pandas - Smoke detection IOT

## Project goal

The goal of this project is to perform data manipulation on the provided dataset of smoke detection IoT data. The Data needs to be organized in a structured format, making it suitable for further analysis.

The dataset contains timestamped data with information such as Node ID, Smoke Flag, Temperature, Humidity, and AQI. However, the data is in a raw format in one column with unnecessary text that needs to be separated into different columns and cleaned before analysis without losing UTC Data.


## Solution

The solution for organizing and cleaning the smoke detection IoT data involves using the Pandas and re libraries in Python. The Pandas library is used for reading and manipulating data in tabular form, and the re library is used for working with regular expressions to extract relevant information from the raw data.

I have created the 𝐞𝐱𝐭𝐫𝐚𝐜𝐭_𝐝𝐚𝐭𝐚 function that looped through each row while preserving the node_id and smoke_flag and updated the current row value in a specific column. The 𝐫𝐞𝐬𝐞𝐭_𝐯𝐚𝐫𝐢𝐚𝐛𝐥𝐞𝐬 function resets all the variables before the next node_id starts.

In [1]:
import pandas as pd

In [2]:
df_smoke_detection_iot = pd.read_csv("Datasets/demo1_smoke_detection_iot.csv")
df_smoke_detection_iot

    1678945311.90692           Node Id:69
0       1.678945e+09         Smoke Flag:0
1       1.678945e+09    Temperature[C]:27
2       1.678945e+09       Humidity[%]:38
3       1.678945e+09  Air Quality[AQI]:67
4       1.678945e+09           Node Id:70
5       1.678945e+09         Smoke Flag:1
6       1.678945e+09    Temperature[C]:32
7       1.678945e+09       Humidity[%]:45
8       1.678945e+09  Air Quality[AQI]:72
9       1.678945e+09           Node Id:69
10      1.678945e+09         Smoke Flag:0
11      1.678945e+09    Temperature[C]:25
12      1.678945e+09       Humidity[%]:32
13      1.678945e+09  Air Quality[AQI]:59
14      1.678945e+09           Node Id:69
15      1.678945e+09         Smoke Flag:0
16      1.678945e+09    Temperature[C]:27
17      1.678945e+09       Humidity[%]:38
18      1.678945e+09  Air Quality[AQI]:67
19      1.678945e+09           Node Id:70
20      1.678945e+09         Smoke Flag:0
21      1.678945e+09    Temperature[C]:27
22      1.678945e+09       Humidity[%]:38
23      1.678945e+09  Air Quality[AQI]:67

## New input format

In [3]:
# Without UTC Data loss
import pandas as pd
import re

# Read the CSV file into a pandas DataFrame
df = pd.read_csv("Datasets/demo1_smoke_detection_iot.csv", header=None, names=['UTC', 'Data'], dtype='str', keep_default_na=False)

final_data = []
# Initialize the columns to None
node_id = smoke_flag = temperature = humidity = aqi = None

def extract_data(utc, node_id, smoke_flag, temperature, humidity, aqi):
    ''' Take all the param and return the dictionary and reset the variables '''
    smoke_data = {
        'UTC': utc,
        'Node Id': node_id,
        'Smoke Flag': smoke_flag,
        'Temperature': temperature,
        'Humidity': humidity,
        'AQI': aqi
    }
    return smoke_data

def reset_variables():
    ''' Reset the variables '''
    # Set global variables to modify the global scope of variable through function
    global node_id, smoke_flag, temperature, humidity, aqi
    if aqi:
        node_id = smoke_flag = temperature = humidity = aqi = None
    else:
        temperature = humidity = aqi = None
    
# Loop through the rows of the DataFrame
for index, row in df.iterrows():
    # Sort the data
    utc = row['UTC']
    if 'node' in row['Data'].lower():
        # Removed the unnecessary text. If you want original data use row['Data']
        node_id = re.sub('[^.0-9]+', '', row['Data'])
        # Append the data     
        final_data.append(extract_data(utc, node_id, smoke_flag, temperature, humidity, aqi))
        reset_variables()
    elif 'smoke' in row['Data'].lower():
        smoke_flag = re.sub('[^.0-9]+', '', row['Data'])
        final_data.append(extract_data(utc, node_id, smoke_flag, temperature, humidity, aqi))
        reset_variables()
    if 'temperature' in row['Data'].lower():
        # Removed the unnecessary text. If you want original data use row['Data']
        temperature = re.sub('[^.0-9]+', '', row['Data'])
        final_data.append(extract_data(utc, node_id, smoke_flag, temperature, humidity, aqi))
        reset_variables()
    elif 'humidity' in row['Data'].lower():
        humidity = re.sub('[^.0-9]+', '', row['Data'])
        final_data.append(extract_data(utc, node_id, smoke_flag, temperature, humidity, aqi))
        reset_variables()
    elif 'aqi' in row['Data'].lower():
        aqi = re.sub('[^.0-9]+', '', row['Data'])   
        final_data.append(extract_data(utc, node_id, smoke_flag, temperature, humidity, aqi))
        reset_variables()
                
# Create a DataFrame with the extracted values
temp_humid_aqi_df = pd.DataFrame(final_data)

# Write the new DataFrame to a CSV file
temp_humid_aqi_df.to_csv('temp_humid_aqi_df.csv', index=False)
print("File saved successfully!")

File saved successfully!

In [5]:
temp_humid_aqi_df

                 UTC Node Id Smoke Flag Temperature Humidity AQI
0   1678945311.90692      69
1   1678945311.90782      69          0
2   1678945311.90982      69          0          27
3   1678945311.91182      69          0                   38
4   1678945311.91277      69          0                       67
5   1678945311.91479      70
6   1678945311.91675      70          1
7   1678945311.91872      70          1          32
8   1678945311.92082      70          1                   45
9    1678945311.9217      70          1                       72
10   1678945311.9237      69
11   1678945311.9258      69          0
12  1678945311.92678      69          0          25
13  1678945311.92878      69          0                   32
14  1678945311.93076      69          0                       59
15   1678945311.9317      69
16  1678945311.93277      69          0
17  1678945325.90601      69          0          27
18  1678945325.90787      69          0                   38
19  1678945325.90981      69          0                       67
20  1678945325.91182      70
21   1678945325.9128      70          0
22  1678945325.91482      70          0          27
23  1678945325.91683      70          0                   38
24    1678945325.918      70          0                       67

## With UTC DATA loss

In [ ]:
# With UTC DATA loss 
import pandas as pd
import re

# Read the CSV file into a pandas DataFrame
df = pd.read_csv("Datasets/demo1_smoke_detection_iot.csv", header=None, names=['UTC', 'Data'], dtype='str', keep_default_na=False)

final_data = []
# Initialize the columns to None
node_id = smoke_flag = temperature = humidity = aqi = None

# Loop through the rows of the DataFrame
for index, row in df.iterrows():
    # Sort the data
    if 'node' in row['Data'].lower():
        # Removed the unnecessary text. If you want original data use row['Data']
        node_id = re.sub('[^.0-9]+', '', row['Data'])
    elif 'smoke' in row['Data'].lower():
        smoke_flag = re.sub('[^.0-9]+', '', row['Data'])
    if 'temperature' in row['Data'].lower():
        # Removed the unnecessary text. If you want original data use row['Data']
        temperature = re.sub('[^.0-9]+', '', row['Data'])
    elif 'humidity' in row['Data'].lower():
        humidity = re.sub('[^.0-9]+', '', row['Data'])
    elif 'aqi' in row['Data'].lower():
        aqi = re.sub('[^.0-9]+', '', row['Data'])
        
        # Append the data at the last element i.e AQI. (All 5 records are store after getting into AQI)
        final_data.append({
            'UTC': row['UTC'],
            'Node Id': node_id,
            'Smoke Flag': smoke_flag,
            'Temperature': temperature,
            'Humidity': humidity,
            'AQI': aqi
        })

        # Reset the temporary variables
        node_id = smoke_flag = temperature = humidity = aqi = None

        
# Create a DataFrame with the extracted values
temp_humid_aqi_df = pd.DataFrame(final_data)

# Write the new DataFrame to a CSV file
temp_humid_aqi_df.to_csv('temp_humid_aqi_df.csv', index=False)
print("File saved successfully!")

## Old Input format

In [ ]:
import pandas as pd
import re

# Read the CSV file into a pandas DataFrame
df = pd.read_csv("Datasets/test_data (2).csv", header=None, names=['UTC', 'Data'], dtype='str', keep_default_na=False)

temp_node_id_data = []
final_data = []
# Initialize the columns to None
humidity = aqi = temperature = node_id = smoke_flag = None

# Loop through the rows of the DataFrame
for index, row in df.iterrows():
    # Extract the previous values for humidity, AQI, and temperature
    if 'temperature' in row['Data'].lower():
        # Remove the unnecessary text. If you want original data use row['Data']
        temperature = re.sub('[^.0-9]+', '', row['Data'])
    elif 'humidity' in row['Data'].lower():
        humidity = re.sub('[^.0-9]+', '', row['Data'])
    elif 'aqi' in row['Data'].lower():
        aqi = re.sub('[^.0-9]+', '', row['Data'])
        # Append the data at the last element i.e AQI. (All 3 records are store after getting into AQI)
        # Save the temporary node id data in list of dictionaries
        temp_node_id_data.append({
            'Temperature': temperature,
            'Humidity': humidity,
            'AQI': aqi
        })

        # Reset the temporary var
        humidity = aqi = temperature = None

    elif 'node' in row['Data'].lower():
        node_id = re.sub('[^.0-9]+', '', row['Data'])
        # Update the data with node_id to temporary data for all the previous data
        for data1 in temp_node_id_data:
            data1['Node ID'] = node_id
    elif 'smoke' in row['Data'].lower():
        smoke_flag = re.sub('[^.0-9]+', '', row['Data'])
        # Update the data with smoke_flag to temporary data for all the previous data and reset the temporary data
        for data2 in temp_node_id_data:
            data2['Smoke Flag'] = smoke_flag

        # Append all the temporary data to final data
        for temp_dict_data in temp_node_id_data:
            final_data.append(temp_dict_data)

        # Reset the temporary Node id data
        temp_node_id_data = []
        node_id = smoke_flag = None


# Create a new DataFrame with the extracted values
temp_humid_aqi_df = pd.DataFrame(final_data)

# Write the new DataFrame to a CSV file
temp_humid_aqi_df.to_csv('temp_humid_aqi_df.csv', index=False)
print("File saved successfully!")

In [ ]:
temp_humid_aqi_df.shape

In [ ]:
temp_humid_aqi_df